#Expyriment 0.9.0 (Python 3.6.3), .xpe-file, coding: UTF-8
#date: Wed Mar 21 2018 14:25:10
#sha1: None
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Linux', node='is153352', release='4.9.8-040908-generic', version='#201702040431 SMP Sat Feb 4 09:32:59 UTC 2017', machine='x86_64', processor='x86_64')
Time,Type,Event,Value,Detail,Detail2
103,stderr,received,'Traceback (most recent call last):'
103,stderr,received,'  File "audiovis.py", line 23, in <module>'
103,stderr,received,"    sounds = [stimuli.Audio('s{:03d}.wav'.format(i)) for i in range(10)]"
103,stderr,received,'  File "audiovis.py", line 23, in <listcomp>'
103,stderr,received,"    sounds = [stimuli.Audio('s{:03d}.wav'.format(i)) for i in range(10)]"
103,stderr,received,'  File "/home/cp983411/anaconda3/lib/python3.6/site-packages/expyriment/stimuli/_audio.py", line 58, in __init__'
103,stderr,received,'    unicode2byte(self._filename)))'
103,stderr,received,"OSError: The audio file b's000.wav' does not exists"
